name: oversight
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  dio: ^5.3.2
  equatable: ^2.0.5
  injectable: ^2.3.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  rxdart: ^0.27.7
  rich_text_controller: ^1.4.2
  flutter_form_builder: ^9.1.1
  logger: ^2.0.2
  form_builder_validators: ^9.0.0
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2
  expansion_tile_card: ^3.0.0
  skeletonizer: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/

fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
    - family: Gilroy-Light
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf